---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9
  - name: debian-8
  - name: fedora-27
  - name: centos-7
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[digitalocean-agent::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
